// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config(); // Load .env
config({ path: ".env.local", override: true }); // Prefer developer overrides when present

const databaseUrl =
  process.env["DATABASE_URL"] ||
  process.env["POSTGRES_URL"] ||
  process.env["PRISMA_DATABASE_URL"];

if (!databaseUrl) {
  console.warn(
    "DATABASE_URL/POSTGRES_URL/PRISMA_DATABASE_URL is not set. Prisma commands may fail without a connection string."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
